# Домашнее задание №1: Классификация. 
# Логистическая регрессия и kNN.

*While the machines are being fixed.*

Формат сдачи будет объявлен позднее. Либо это будет проверяющая система, либо telegram-бот. 

<span style="color: red; font-size: 14pt">Дедлайны: 
* ФИВТ, третий курс - 4 марта 23:59
* Открытый курс - 7 марта, 23:59
</span>

### Часть 1. Небольшой numpy-разогрев. (10%)

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Создайте случайную матрицу A размерами 10 на 10 из целых чисел от 0 до 100
# hint: np.random.randint
A = np.random.randint(0,100,(10,10))
A
# Ваш код здесь

array([[72, 37, 25, 59, 88,  0, 80, 96, 12, 30],
       [58, 57, 44, 63, 12, 77, 41, 62, 17, 75],
       [24, 39, 18, 86, 71, 82, 42, 92, 68, 91],
       [38, 80, 50, 31, 65, 23, 23,  3, 75, 45],
       [ 5, 36, 93, 55, 76, 17, 67, 82, 72, 66],
       [53, 73, 41,  3,  6, 34, 48,  2, 89, 31],
       [55, 78, 77, 13, 42, 28,  9, 39, 44, 95],
       [45, 53, 43, 75, 42, 69, 81, 25, 63, 93],
       [ 6, 37, 34, 23, 81, 30, 11, 74, 84, 80],
       [ 4, 85, 34, 79, 30, 80, 45,  2, 17, 65]])

In [3]:
# Посчитайте средние значения в матрице по столбцам
A.mean(axis = 0)
# Ваш код здесь

array([36. , 57.5, 45.9, 48.7, 51.3, 44. , 44.7, 47.7, 54.1, 67.1])

In [4]:
# Транспонируйте матрицу A
A.T
# Ваш код здесь

array([[72, 58, 24, 38,  5, 53, 55, 45,  6,  4],
       [37, 57, 39, 80, 36, 73, 78, 53, 37, 85],
       [25, 44, 18, 50, 93, 41, 77, 43, 34, 34],
       [59, 63, 86, 31, 55,  3, 13, 75, 23, 79],
       [88, 12, 71, 65, 76,  6, 42, 42, 81, 30],
       [ 0, 77, 82, 23, 17, 34, 28, 69, 30, 80],
       [80, 41, 42, 23, 67, 48,  9, 81, 11, 45],
       [96, 62, 92,  3, 82,  2, 39, 25, 74,  2],
       [12, 17, 68, 75, 72, 89, 44, 63, 84, 17],
       [30, 75, 91, 45, 66, 31, 95, 93, 80, 65]])

In [5]:
# Перемножьте поэлементно матрицу A и транспонированную матрицу A 
A * A.T
# Ваш код здесь

array([[5184, 2146,  600, 2242,  440,    0, 4400, 4320,   72,  120],
       [2146, 3249, 1716, 5040,  432, 5621, 3198, 3286,  629, 6375],
       [ 600, 1716,  324, 4300, 6603, 3362, 3234, 3956, 2312, 3094],
       [2242, 5040, 4300,  961, 3575,   69,  299,  225, 1725, 3555],
       [ 440,  432, 6603, 3575, 5776,  102, 2814, 3444, 5832, 1980],
       [   0, 5621, 3362,   69,  102, 1156, 1344,  138, 2670, 2480],
       [4400, 3198, 3234,  299, 2814, 1344,   81, 3159,  484, 4275],
       [4320, 3286, 3956,  225, 3444,  138, 3159,  625, 4662,  186],
       [  72,  629, 2312, 1725, 5832, 2670,  484, 4662, 7056, 1360],
       [ 120, 6375, 3094, 3555, 1980, 2480, 4275,  186, 1360, 4225]])

In [6]:
# Посчитайте dot product (результат матричного умножения) матрицы A на саму себя и запишите в матрицу B
# https://en.wikipedia.org/wiki/Dot_product
B = A.dot(A)
B
# Ваш код здесь

array([[19524, 27958, 26728, 26284, 28342, 19376, 25558, 25367, 25040,
        35111],
       [20520, 31692, 21124, 25140, 22334, 24204, 23727, 19034, 25512,
        31929],
       [19613, 37638, 29501, 28437, 29202, 27296, 27619, 21774, 35938,
        40282],
       [13328, 22968, 19888, 21991, 23464, 19561, 17892, 25289, 22534,
        29477],
       [16122, 32087, 27275, 30388, 30998, 28507, 23962, 27822, 33390,
        43372],
       [14368, 20437, 15239, 17047, 19545, 16942, 14026, 22525, 18589,
        26262],
       [15414, 26552, 18993, 29137, 23878, 26148, 23288, 25511, 21877,
        32909],
       [20393, 36791, 27332, 26258, 28475, 25715, 23062, 24001, 31167,
        38629],
       [11022, 25291, 21908, 24812, 23991, 22897, 21438, 21424, 26802,
        33207],
       [16353, 29329, 20811, 19115, 16982, 21488, 16579, 14832, 23649,
        27650]])

### Часть 2. Логистическая регрессия и kNN.

Будем работать с подвыборкой из [данных о типе лесного покрытия из репозитория UCI](http://archive.ics.uci.edu/ml/datasets/Covertype). Доступно 7 различных классов. Каждый объект описывается 54 признаками, 40 из которых являются бинарными. Описание данных доступно по ссылке, а так же в файле `covtype.info.txt`.

In [7]:
all_data = pd.read_csv('forest_dataset.csv')

Выделите 20% данных в `delayed_data` в качестве выборки, на которой будет производиться финальное сравнение моделей, в `all_data` поместите оставшиеся 80%.

In [8]:
delayed_data, all_data = train_test_split

NameError: name 'train_test_split' is not defined

Выделим значения метки класса в переменную `labels`, признаковые описания в переменную `feature_matrix`. Так как данные числовые и не имеют пропусков, переведем их в `numpy`-формат с помощью метода `.values`.

In [12]:
labels = all_data[all_data.columns[-1]].values
feature_matrix = all_data[all_data.columns[:-1]].values

[[2683  333   35 ...    0    0    0]
 [2915   90    8 ...    0    0    0]
 [2941  162    7 ...    0    0    0]
 ...
 [2693   21   11 ...    0    0    0]
 [2536   42   11 ...    0    0    0]
 [3109  261   10 ...    0    0    0]]


#### 2.1 Двуклассовая классификация (10%)

Для начала будем работать только с двумя типами лесного покрытия. Обучите линейный классификатор для разделения двух классов. Данные разделите на train и test с помощью `train_test_split`.

In [13]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score

In [14]:
two_class_labels_indices = (labels == 1) + (labels == 2)

two_class_feature_matrix = feature_matrix[two_class_labels_indices]
two_class_labels = labels[two_class_labels_indices]

In [31]:
train_feature_matrix, test_feature_matrix, train_labels, test_labels = train_test_split(feature_matrix, labels, test_size = 0.2, shuffle=True, random_state=42)

In [53]:
train_feature_matrix.shape

(8000, 54)

Обучите логистическую регрессию. Оцените качество классификации на отложенной выборке с помощью `accuracy` и `f1_score` ([Wikipedia](https://en.wikipedia.org/wiki/F1_score)).

In [54]:
lr_clf = LogisticRegression()
lr_clf.fit(train_feature_matrix, train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [55]:
predictions = lr_clf.predict(test_feature_matrix)
accuracy_score(test_labels, predictions)

0.6945

In [57]:
f1_score(test_labels, predictions, average='micro')

0.6945

#### 2.2 Многоклассовая классификация: логистическая регрессия (40%)

**Комментарий:**

*Логистическая регрессия позволяет решать и задачу многоклассовой классификации. Класс ``LogisticRegression`` позвляет это делать двумя способами:* 
- *1. Стандартный One vs Rest (т.е. каждый класс отделяется от всех других). Параметр `multi_class='ovr'`.*
- *2. Используюя кросс-энтропию (оценивается сразу вектор вероятностей принадлежности классам). Параметр `multi_class='multinomial'`.*

*По умолчанию будем использовать второй способ.*


Теперь будем работать со всеми 7 типами покрытия (данные уже находятся в переменных `feature_matrix` и `labels`, если Вы их не переопределили). Разделите выборку на обучающую и тестовую с помощью метода `train_test_split`, используйте значения параметров `test_size=0.2`, `random_state=42`. Обучите логистическую регрессию  на данном датасете.

In [70]:
lr_clf = LogisticRegression(multi_class='multinomial', solver = 'sag', max_iter = 5000)
lr_clf.fit(train_feature_matrix, train_labels)
# Ваш код здесь

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=5000, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='sag',
          tol=0.0001, verbose=0, warm_start=False)

С помощью 5-кратной кросс-валидации (`GridSearchCV`) подберите оптимальное значение параметров `С` и `penalty`. Для параметра `C` используйте набор значений `np.linspace(0.01, 1, 10)`, а для `penalty` - `['l1', 'l2']`. Критерий качества `scoring = 'accuracy'`.

In [71]:
parameters = {'penalty':['l1', 'l2'], 'C':np.linspace(0.01, 1, 10)}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(lr_clf, parameters, scoring = 'accuracy', cv = 5)

Постройте графики средних значений критерия качества `accuracy` для типов регуляризации `l1` и `l2` в зависимости от коэффициента регуляризации `C`.

In [73]:
grid.fit(train_feature_matrix, train_labels)
#print(grid.grid_scores_)

ValueError: Solver sag supports only l2 penalties, got l1 penalty.

Проанализируйте полученные графики. Чему равны найденные оптимальные значения параметров `C` и `penalty`?

In [0]:
# Ваш код здесь

Используя найденные оптимальные значения `C` и `penalty`, обучите логистическую регрессию на обучающей выборке (train) и вычислите вероятности принадлежности к классам для тестовой (test)  выборки (`best_lr_clf.predict_proba`).

In [0]:
best_lr_clf = LogisticRegression(<your_best_params_here>)

# Ваш код здесь

Для полученной матрицы вычислите усредненные по всем объектам из тестовой выборки значения вероятностей принадлежности к классам. Сравните ее оценкой вероятности принадлежности к классу на основе частот меток классов в обучающей выборке.

In [0]:
# Ваш код здесь

#### 2.3 Многоклассовая классификация: kNN (30%).

Вспомним первое занятие. Обучите на том же датасете `KNeighborsClassifier` из `sklearn`.

In [0]:
from sklearn.neighbors import KNeighborsClassifier

# Ваш код здесь

Попробуйте использовать различные стратегии вычисления весов: `[‘uniform’, ‘distance’]`. Выберите одно из них самостоятельно. Чем обоснован Ваш выбор?

Переберите по сетке от `1` до `10` параметр числа соседей. Покажите на графике, как менялись значения критерия качества `accuracy` при изменении числа соседей.

In [0]:
# Ваш код здесь

Используя найденное оптимальное число соседей, вычислите вероятности принадлежности к классам для тестовой выборки (`.predict_proba`).

In [0]:
# Ваш код здесь

#### 2.4 Сравнение результатов логистической регрессии и kNN (10%).

В реальной жизни новые данные становятся доступны с течением времени. Сравните качество Вашей лучшей модели логистической регресии и лучшего kNN  на отложенной выборке `delayed_data`. Какая из моделей показала лучший результат?

In [0]:
# Ваш код здесь